# Generated by Django 5.0.4 on 2024-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE(R)', 'CSE(Regular)'), ('CSE(H)', 'CSE(HONORS)'), ('CSIT', 'CS&IT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Prof.', 'Professor'), ('Assoc. Prof', 'Assoc Professor'), ('Asst. Prof', 'Assistant professor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(choices=[('MD', 'MD'), ('PHD', 'PHD'), ('Dr.', 'Dr.')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('B.com', 'B.com')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN'), ('SUMMER', 'SUMMER')], max_length=20),
        ),
    ]
