# Generated by Django 5.0.4 on 2024-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_course_department_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='CSE', max_length=50),
            preserve_default=False,
        ),
    ]
